### ISSUE TITLE
npm install react-bootstrap doesn't work (with browserify ?)

### ISSUE THREAD

**Issue by dvine-multimedia** [react-bootstrap/react-bootstrap-npm#2]
I just installed react-boostrap via npm. Then I used require('react-bootstrap').Input in a file and ran it through browserify. This resulted in:
Error: Cannot find module 'react-bootstrap' from [my/current/src/folder]
The package.js specifies, that there should be a main.js in the lib/ folder. But that folder is empty except for a README.md and another package.js.
Then I copied the contents of the react-bootstrap-npm repo in the lib/ folder by and and it worked.

Am I missing something here or is this really a bug?

**Comment by mtscout6** [comment]
Are you still seeing this issue? Also, please submit future issues to the source repo at https://github.com/react-bootstrap/react-bootstrap.
